### ISSUE TITLE
Q: how to build  sphinx-inline-tabs in build env without access to network?

### ISSUE THREAD

**Issue by kloczek** [pradyunsg/sphinx-inline-tabs#17]
Looks like sphinx-inline-tabs is not using setuptools and I cannot find anywhere here any instruction about how to build, install and test sphinx-inline-tabs in build env cut off from access to the network.
Any advice how to do that?

**Comment by pradyunsg** [comment]
You need a Python environment containing `flit_core` and `build` projects from PyPI.

Run `python3 -m build --no-isolation` to get a wheel distribution of this project. The wheel can be installed using `pip install path/to/file.whl`.

You can pass `--no-index` to pip, if you don't want it to access the network (unless you have a custom index) and/or pass `--no-deps` to pip if you want to install the dependencies yourself.

**Comment by kloczek** [comment]
OK I have now packaged `build` and need to package second module.
Thx. Will back showrly :)

**Comment by pradyunsg** [comment]
I assume this has been resolved now?

**Comment by kloczek** [comment]
Still not .. :(
I just back to build all necessary dependencies.
As seems sphinx-inline-tabs requires flit_core:
```console
+ cd sphinx-inline-tabs-2021.04.11.beta9
+ /usr/bin/python3 -m build --no-isolation
ERROR Backend 'flit_core.buildapi' is not available.
error: Bad exit status from /var/tmp/rpm-tmp.cAWf2V (%build)
```
I've been trying to package that module as well and to be honets Looks like I've hot some issue:
```console
+ cd flit-3.2.0
+ cd flit_core
+ /usr/bin/python3 -m build --no-isolation
+ cd -
/home/tkloczko/rpmbuild/BUILD/flit-3.2.0
+ /usr/bin/python3 -m build --no-isolation
ERROR Backend 'flit_core.buildapi' is not available.
```
Can we hol that ticket opened for next few days?

**Comment by kloczek** [comment]
Looking on `flit-3.2.0/flit_core` in flint module like `build` module build something however looking on `build` module help output I don't see how to install and test it.
Do you know what is the normal metwhodoilogy of the isntall and test in case of modules with `pyproject.toml` file?

**Comment by kloczek** [comment]
OK. I've manage to build `sphinx-inline-tabs`
Closing.

Thank you.

BTW do you have any plans to make soon final (non-beta) release? :)
